### ISSUE TITLE
inject method ??

### ISSUE THREAD

**Issue by codixor** [Wandu/DI#1]
very nice job, but still how to use inject function "public function inject($object, array $parameters = [])"

**Comment by wan2land** [comment]
sorry for not enough documents.
so, i have prepared a example for you.

this is phpunit testcase file,
https://github.com/Wandu/DI/blob/master/tests/InjectTest.php

and this is test files used in testcase above.
https://github.com/Wandu/DI/tree/master/tests/Stub/Inject

enough? :D

**Comment by codixor** [comment]
thnk you very much :)
